version: '3.8'

services:
  db:
    image: postgis/postgis:14-master
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: thu
      POSTGRES_PASSWORD: dev123
      POSTGRES_DB: osty
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
